name: voice-assistant
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.14
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cffi=1.17.1
  - expat=2.7.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - jack=1.9.22
  - lame=3.100
  - ld_impl_linux-64=2.40
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libiconv=1.18
  - liblapack=3.9.0
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopus=1.5.2
  - libsndfile=1.2.2
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libxcb=1.17.0
  - mpg123=1.32.9
  - ncurses=6.5
  - openssl=3.5.2
  - pip=25.1
  - portaudio=19.7.0
  - pthread-stubs=0.3
  - pyaudio=0.2.14
  - pycparser=2.22
  - pysoundfile=0.13.1
  - python=3.10.18
  - python_abi=3.10
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyascii==0.3.3
      - anyio==4.10.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - babel==2.17.0
      - bangla==0.0.5
      - blinker==1.9.0
      - blis==1.2.1
      - bnnumerizer==0.0.2
      - bnunicodenormalizer==0.1.7
      - catalogue==2.0.10
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.1.8
      - cloudpathlib==0.21.1
      - coloredlogs==15.0.1
      - confection==0.1.5
      - contourpy==1.2.1
      - coqpit==0.0.17
      - cycler==0.12.1
      - cymem==2.0.11
      - cython==3.1.3
      - dateparser==1.1.8
      - decorator==5.2.1
      - docopt==0.6.2
      - einops==0.8.1
      - en-core-web-sm==3.8.0
      - encodec==0.1.1
      - exceptiongroup==1.3.0
      - fastapi==0.116.1
      - filelock==3.19.1
      - flask==3.1.2
      - flatbuffers==25.9.23
      - fonttools==4.59.1
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - g2pkk==0.1.2
      - gensim==4.3.3
      - grpcio==1.74.0
      - gruut==2.2.3
      - gruut-ipa==0.13.0
      - gruut-lang-de==2.0.1
      - gruut-lang-en==2.0.1
      - gruut-lang-es==2.0.1
      - gruut-lang-fr==2.0.2
      - gtts==2.5.4
      - h11==0.16.0
      - h2==4.3.0
      - hangul-romanize==0.1.0
      - hf-xet==1.1.8
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - humanfriendly==10.0
      - hyperframe==6.1.0
      - idna==3.10
      - inflect==7.5.0
      - itsdangerous==2.2.0
      - jamo==0.4.1
      - jieba==0.42.1
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonlines==1.2.0
      - kiwisolver==1.4.9
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - librosa==0.10.0
      - llvmlite==0.43.0
      - marisa-trie==1.3.1
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - milvus-lite==2.5.1
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.4
      - murmurhash==1.0.13
      - networkx==2.8.8
      - nltk==3.9.1
      - num2words==0.5.14
      - numba==0.60.0
      - numpy==1.22.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - onnxruntime==1.23.0
      - openai-whisper==20250625
      - packaging==25.0
      - pandas==1.5.3
      - pillow==11.3.0
      - platformdirs==4.4.0
      - pooch==1.8.2
      - portalocker==3.2.0
      - preshed==3.0.10
      - propcache==0.3.2
      - protobuf==6.32.0
      - psutil==7.0.0
      - pvporcupine==3.0.5
      - pvporcupinedemo==3.0.5
      - pvrecorder==1.2.4
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pymilvus==2.6.2
      - pymilvus-model==0.3.2
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pypinyin==0.55.0
      - pysbd==0.3.4
      - python-crfsuite==0.9.11
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pyttsx3==2.99
      - pytz==2025.2
      - pyyaml==6.0.2
      - qdrant-client==1.15.1
      - regex==2025.7.34
      - requests==2.32.5
      - rich==14.1.0
      - safetensors==0.6.2
      - samplerate==0.2.1
      - scikit-learn==1.7.1
      - scipy==1.11.4
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.3.0.post1
      - sniffio==1.3.1
      - sounddevice==0.5.2
      - soxr==0.5.0.post1
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - starlette==0.47.3
      - sudachidict-core==20250515
      - sudachipy==0.6.10
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - thinc==8.3.4
      - threadpoolctl==3.6.0
      - tiktoken==0.11.0
      - tokenizers==0.21.4
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - trainer==0.0.36
      - transformers==4.55.4
      - triton==3.4.0
      - tts==0.22.0
      - typeguard==4.4.4
      - typer==0.16.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzlocal==5.3.1
      - ujson==5.11.0
      - umap-learn==0.5.7
      - unidecode==1.4.0
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - webrtcvad==2.0.10
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - yarl==1.20.1
prefix: /home/satwik/miniconda3/envs/voice-assistant
